-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- 1. Create PROFILES table (Public profile for each user)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  avatar_url text,
  updated_at timestamp with time zone
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Function to handle new user signup automatically
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. Create ITEMS table (The Closet)
create table public.items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  name text not null,
  brand text,
  category text,
  image_url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.items enable row level security;

create policy "Items are viewable by owner."
  on items for select
  using ( auth.uid() = user_id );

create policy "Items are insertable by owner."
  on items for insert
  with check ( auth.uid() = user_id );

create policy "Items are updatable by owner."
  on items for update
  using ( auth.uid() = user_id );

create policy "Items are deletable by owner."
  on items for delete
  using ( auth.uid() = user_id );

-- 3. Create OUTFITS table (Saved or Generated Outfits)
create table public.outfits (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  name text,
  description text,
  image_url text,
  season text,
  event_type text,
  items jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.outfits enable row level security;

create policy "Outfits are viewable by owner."
  on outfits for select
  using ( auth.uid() = user_id );

create policy "Outfits are insertable by owner."
  on outfits for insert
  with check ( auth.uid() = user_id );

-- 4. INSERT MOCK DATA (Optional - Remove user_id enforcement for mock data or manually assign to your user ID)
-- IMPORTANT: These inserts will fail if you run them without an active user session in the SQL editor context
-- usually. Or if RLS is on and you are authenticated as 'service_role', they might work.
-- A better approach for initial testing in Supabase SQL Editor is to just create the table structure.

-- However, if you want "public" demo items visible to everyone (for testing before login),
-- you could add a policy:
-- create policy "Public items are viewable" on items for select using (user_id is null);
-- and then insert items with user_id = null. 
